# Following steps need to be run manually
# sudo curl -L -o /etc/yum.repos.d/gh-cli.repo https://cli.github.com/packages/rpm/gh-cli.repo
# sudo dnf install gh -y
# gh auth login -s admin:org
# will autmoate this with bash
- name: SetUpPrompt
  ansible.builtin.shell: set-prompt github-runner

- name: Add Github runner user
  ansible.builtin.user:
    name: grunner


- name: Create github directory
  ansible.builtin.file:
    path: /actions-runner
    state: directory
    owner: grunner
    group: grunner

- name: Download and Extract Runner
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.322.0/actions-runner-linux-x64-2.322.0.tar.gz
    dest: "/actions-runner"
    remote_src: yes
    owner: grunner
    group: grunner

#- name: Packages for the GitHub CLI
#  ansible.builtin.get_url:
#    url: https://cli.github.com/packages/rpm/gh-cli.repo
#    dest: /etc/yum.repos.d/gh-cli.repo

#- name: Install github cli
#  ansible.builtin.dnf:
#    name: gh
#    state: latest

- name: Grab token
  ansible.builtin.shell: |
    /usr/bin/gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/kuppalaORG/actions/runners/registration-token | /usr/bin/jq .token
  register: out
  become_user: ec2-user


- name: Print token
  ansible.builtin.debug:
    msg: " {{ out }} "

- name: Install libicu dependencies
  ansible.builtin.package:
    name: libicu
    state: latest

- name: Get the runner count
  ansible.builtin.shell: |
    gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/kuppalaORG/actions/runners | jq .total_count |xargs
  register: runner_count
  become_user: ec2-user

- name: Get the runner status
  ansible.builtin.shell: |
    gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/kuppalaORG/actions/runners | jq '.runners[] | select(.name == "ec2") | .status' |xargs
  register: runner_status
  become_user: ec2-user

- name: Print runner status
  ansible.builtin.debug:
    msg: " {{ runner_status }} "


- name: Configure Github Runner
  ansible.builtin.shell: ./config.sh --url https://github.com/kuppalaORG --token {{ out.stdout }} --runnergroup Default --name ec2 --labels rhel --work _work --replace
  become_user: grunner
  args:
    chdir: /actions-runner
  when: runner_count.stdout == "0" or runner_status.stdout == "offline"

- name: Update Path file
  ansible.builtin.copy:
    src: path
    dest: /actions-runner/.path
  become_user: grunner
  when: runner_count.stdout == "0" or runner_status.stdout == "offline"

- name: Install Runner Service
  ansible.builtin.shell: ./svc.sh install grunner ; ./svc.sh start
  args:
    chdir: /actions-runner
  become: true
  when: runner_count.stdout == "0" or runner_status.stdout == "offline"

- name: Download Terraform Repo file
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install Terraform
  ansible.builtin.dnf:
    name: terraform
    state: latest

- name: Install Ansible
  ansible.builtin.shell: pip-3.11 install ansible