---
- name: Retrieve MySQL Secrets from Vault
  hosts: localhost
  tasks:
    - name: Retrieve secrets from HashiCorp Vault
      ansible.builtin.debug:
        msg: >-
          {{
            lookup(
              'hashi_vault',
              'secret=roboshop-dev/data/mysql token={{ vault_token }} url=http://vault-internal.codedeploywithbharath.tech:8200 validate_certs=false'
            )
          }}
