name: grab vault value
on: [ workflow_dispatch]
jobs:
  DEV:
    runs-on: self-hosted
    steps:
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: http://vault-internal.codedeploywithbharath.tech:8200
          token: ${{ secrets.VAULT_TOKEN }}
          tlsSkipVerify: true
          secrets: |
            roboshop-dev/data/mysql;
      - run: env