name: Run vault setup
on: [workflow_dispatch]
jobs:
  Provision:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: echo $PATH
      - run: echo ${{ secrets.SSH_USER }}
      - run: echo ${{ secrets.VAULT_TOKEN }}
      - run: echo ${{ secrets.VAULT_UNSEAL_KEY }}
      - name: Run Your vault
        run: ansible-playbook -i vault-internal.codedeploywithbharath.tech, tool-setup.yml -e ansible_user=${{ secrets.SSH_USER }} -e ansible_password=${{ secrets.SSH_PASS }} -e tool_name=vault

#      - name: Print Environment Variables (Debugging)
#      - run: printenv | grep "SECRET"

      - name: Run Playbook
        run: |
          ansible-playbook test_vault.yml \
            --extra-vars '{"vault_unseal_key": "${{ secrets.VAULT_UNSEAL_KEY }}", "vault_token": "${{ secrets.VAULT_TOKEN }}"}'
