name: Run vault setup
on: [workflow_dispatch]
jobs:
  Provision:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: echo $PATH
      - run: echo ${{ secrets.SSH_USER }}
      - run: echo ${{ secrets.VAULT_TOKEN }}
      - name: Run Your vault
        run: ansible-playbook -i vault-internal.codedeploywithbharath.tech, tool-setup.yml -e ansible_user=${{ secrets.SSH_USER }} -e ansible_password=${{ secrets.SSH_PASS }} -e tool_name=vault
      - name: Retrieve MySQL secrets from Vault
        run: |
          echo $(ansible localhost -m ansible.builtin.debug -a "msg={{ lookup('hashi_vault', 'secret=roboshop-dev/data/mysql token=${{ secrets.VAULT_TOKEN }} url=http://vault-internal.codedeploywithbharath.tech validate_certs=false') }}")
